# Generated by Django 5.2.8 on 2025-12-17 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier_type', models.CharField(choices=[('api_key', 'API Key'), ('ip_address', 'IP Address')], max_length=20)),
                ('identifier_value', models.CharField(db_index=True, max_length=255)),
                ('identifier_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('emails_sent_current_hour', models.PositiveIntegerField(default=0)),
                ('emails_sent_current_day', models.PositiveIntegerField(default=0)),
                ('emails_sent_total', models.PositiveIntegerField(default=0)),
                ('is_blocked', models.BooleanField(default=False)),
                ('block_reason', models.CharField(blank=True, max_length=255)),
                ('block_until', models.DateTimeField(blank=True, null=True)),
                ('last_request_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('identifier_type', 'identifier_hash')},
            },
        ),
        migrations.CreateModel(
            name='EmailSendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('message_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('from_address', models.EmailField(max_length=254)),
                ('to_addresses', models.JSONField()),
                ('cc_addresses', models.JSONField(blank=True, default=list)),
                ('bcc_addresses', models.JSONField(blank=True, default=list)),
                ('subject', models.CharField(max_length=200)),
                ('template_used', models.CharField(blank=True, max_length=100)),
                ('template_variables', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('bounced', 'Bounced'), ('complained', 'Complained'), ('delivery_delayed', 'Delivery Delayed'), ('failed', 'Failed'), ('pending', 'Pending')], db_index=True, default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('is_retryable', models.BooleanField(default=False)),
                ('attachment_count', models.PositiveIntegerField(default=0)),
                ('total_attachment_size', models.PositiveIntegerField(default=0)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('api_key_hash', models.CharField(blank=True, max_length=64)),
                ('tags', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='emails_emai_status_b82a4f_idx'), models.Index(fields=['from_address', 'created_at'], name='emails_emai_from_ad_d82cff_idx'), models.Index(fields=['message_id'], name='emails_emai_message_9663a4_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size', models.PositiveIntegerField()),
                ('s3_url', models.URLField(blank=True)),
                ('upload_status', models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='emails.emailsendlog')),
            ],
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('template_type', models.CharField(choices=[('appointment_confirmation', 'Appointment Confirmation'), ('appointment_reminder', 'Appointment Reminder'), ('appointment_cancelled', 'Appointment Cancelled'), ('welcome', 'Welcome Email'), ('doctor_new_appointment', 'Doctor New Appointment'), ('custom', 'Custom Template')], max_length=50)),
                ('subject', models.CharField(max_length=200)),
                ('html_content', models.TextField()),
                ('text_content', models.TextField(blank=True)),
                ('variables_required', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['template_type', 'is_active'], name='emails_emai_templat_7dc99b_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailSESEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('send', 'Send'), ('delivery', 'Delivery'), ('open', 'Open'), ('click', 'Click'), ('bounce', 'Bounce'), ('complaint', 'Complaint'), ('delivery_delay', 'Delivery Delay'), ('subscription', 'Subscription')], db_index=True, max_length=20)),
                ('event_timestamp', models.DateTimeField(db_index=True)),
                ('ses_message_id', models.CharField(blank=True, max_length=255)),
                ('bounce_type', models.CharField(blank=True, choices=[('permanent', 'Permanent'), ('transient', 'Transient')], max_length=20)),
                ('bounced_recipients', models.JSONField(blank=True, default=list)),
                ('complained_recipients', models.JSONField(blank=True, default=list)),
                ('bounce_subtype', models.CharField(blank=True, max_length=100)),
                ('raw_event_data', models.JSONField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ses_events', to='emails.emailsendlog')),
            ],
            options={
                'ordering': ['-event_timestamp'],
                'indexes': [models.Index(fields=['event_type', 'event_timestamp'], name='emails_emai_event_t_761cfd_idx'), models.Index(fields=['email_log', 'event_type'], name='emails_emai_email_l_af6f2f_idx')],
            },
        ),
    ]
